# Generated by Django 2.1.3 on 2019-01-21 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=50)),
                ('body', models.CharField(max_length=4, null=True, verbose_name='blog_column_body')),
                ('caption', models.CharField(max_length=500)),
                ('url', models.URLField()),
                ('app', models.CharField(default='photo', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'photo',
                'db_table': 'photo',
            },
        ),
        migrations.CreateModel(
            name='PhotoReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_replies', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='MyPhoto.Photo')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_replied', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'PhotoReply',
                'db_table': 'photo_reply',
            },
        ),
        migrations.CreateModel(
            name='PhotoSubReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('to_reply', models.IntegerField(default=0)),
                ('parent_reply', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_sub_replies', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='MyPhoto.Photo')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='MyPhoto.PhotoReply')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_sub_replied', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'PhotoSubReply',
                'db_table': 'photo_sub_reply',
            },
        ),
    ]
