# Generated by Django 2.1.3 on 2019-01-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPhoto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'verbose_name': 'photo'},
        ),
        migrations.AlterModelTable(
            name='photo',
            table='photo',
        ),
    ]
