# Generated by Django 2.1.3 on 2019-01-05 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyPhoto', '0002_auto_20190105_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo',
            new_name='url',
        ),
    ]
