# Generated by Django 2.1.3 on 2019-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPhoto', '0002_remove_photo_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='body',
            field=models.CharField(max_length=4, null=True, verbose_name='blog_column_body'),
        ),
    ]
