# Generated by Django 2.1.3 on 2019-01-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyPhoto', '0003_auto_20190105_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_replies', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='MyPhoto.Photo')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_replied', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'PhotoReply',
                'db_table': 'photo_reply',
            },
        ),
    ]
