# Generated by Django 2.1.3 on 2019-01-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPhoto', '0004_photoreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoreply',
            name='parent_reply',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photoreply',
            name='to_reply',
            field=models.IntegerField(default=0),
        ),
    ]
