# Generated by Django 2.1.3 on 2019-01-08 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyPhoto', '0005_auto_20190107_2321'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoSubReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('to_reply', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_sub_replies', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='MyPhoto.PhotoReply')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_sub_replied', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'PhotoSubReply',
                'db_table': 'photo_sub_reply',
            },
        ),
    ]
