# Generated by Django 2.1.3 on 2019-01-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyPhoto', '0006_photosubreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosubreply',
            name='photo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyPhoto.Photo'),
            preserve_default=False,
        ),
    ]
