# Generated by Django 2.1.3 on 2019-01-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyPhoto', '0007_photosubreply_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photosubreply',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='MyPhoto.Photo'),
        ),
    ]
