# Generated by Django 2.1.3 on 2019-01-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPhoto', '0008_auto_20190108_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoreply',
            name='parent_reply',
        ),
        migrations.RemoveField(
            model_name='photoreply',
            name='to_reply',
        ),
        migrations.AddField(
            model_name='photosubreply',
            name='parent_reply',
            field=models.IntegerField(default=0),
        ),
    ]
