# Generated by Django 2.1.3 on 2019-01-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0002_auto_20190121_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='app',
            field=models.CharField(default='photo', max_length=40),
        ),
    ]
