# Generated by Django 2.1.3 on 2019-01-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0003_auto_20190121_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='action',
            field=models.CharField(default='', max_length=20),
        ),
    ]
