# Generated by Django 2.1.3 on 2019-01-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MyBlog', '0001_initial'),
        ('MyPhoto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('blogs', models.ManyToManyField(related_name='tags', to='MyBlog.Blog')),
                ('photos', models.ManyToManyField(related_name='tags', to='MyPhoto.Photo')),
            ],
            options={
                'verbose_name': 'Tag',
                'db_table': 'tag',
            },
        ),
    ]
