# Generated by Django 2.1.3 on 2019-01-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0003_auto_20190124_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='blogs',
            field=models.ManyToManyField(to='MyBlog.Blog'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='photos',
            field=models.ManyToManyField(to='MyPhoto.Photo'),
        ),
    ]
