# Generated by Django 2.1.3 on 2019-01-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tag', '0004_auto_20190124_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='blogs',
            field=models.ManyToManyField(related_name='tags', to='MyBlog.Blog'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='photos',
            field=models.ManyToManyField(related_name='tags', to='MyPhoto.Photo'),
        ),
    ]
