# Generated by Django 2.1.3 on 2019-01-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
    ]
