# Generated by Django 2.1.3 on 2019-01-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_auto_20190125_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='caption',
            field=models.CharField(max_length=4, null=True, verbose_name='photo_column_caption'),
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(max_length=4, null=True, verbose_name='photo_column_url'),
        ),
    ]
