# Generated by Django 2.1.3 on 2019-01-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_auto_20181231_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(default='6SOM199ARFy3SI2RorS6rQ', max_length=22, primary_key=True, serialize=False),
        ),
    ]
