# Generated by Django 2.1.3 on 2018-12-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0002_blogreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreply',
            name='parent_reply',
            field=models.IntegerField(default=0),
        ),
    ]
