# Generated by Django 2.1.3 on 2019-02-01 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_auto_20190131_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='url',
        ),
    ]
