# Generated by Django 2.1.3 on 2018-12-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_blogreply_parent_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogreply',
            options={'verbose_name': 'BlogReply'},
        ),
        migrations.AlterModelTable(
            name='blogreply',
            table='blog_reply',
        ),
    ]
