# Generated by Django 2.1.3 on 2019-01-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0003_auto_20190104_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.CharField(max_length=22, primary_key=True, serialize=False),
        ),
    ]
