# Generated by Django 2.1.3 on 2019-01-07 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_auto_20190105_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogreply',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_replies', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='blogreply',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_replied', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
