# Generated by Django 2.1.3 on 2018-12-13 13:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0004_auto_20181213_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogreply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogreply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
