# Generated by Django 2.1.3 on 2019-01-08 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyBlog', '0005_auto_20190107_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSubReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1000)),
                ('to_reply', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sub_replies', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'BlogSubReply',
                'db_table': 'blog_sub_reply',
            },
        ),
        migrations.RemoveField(
            model_name='blogreply',
            name='parent_reply',
        ),
        migrations.RemoveField(
            model_name='blogreply',
            name='to_reply',
        ),
        migrations.AddField(
            model_name='blogsubreply',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='MyBlog.BlogReply'),
        ),
        migrations.AddField(
            model_name='blogsubreply',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_sub_replied', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
