# Generated by Django 2.1.3 on 2019-01-08 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0006_auto_20190108_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsubreply',
            name='blog',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='MyBlog.Blog'),
            preserve_default=False,
        ),
    ]
