# Generated by Django 2.1.3 on 2019-01-08 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0007_blogsubreply_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsubreply',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_replies', to='MyBlog.Blog'),
        ),
    ]
