# Generated by Django 2.1.3 on 2019-01-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyBlog', '0008_auto_20190108_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='app',
            field=models.CharField(default='blog', max_length=10),
        ),
        migrations.AddField(
            model_name='blog',
            name='caption',
            field=models.CharField(max_length=4, null=True, verbose_name='photo_column_caption'),
        ),
        migrations.AddField(
            model_name='blog',
            name='url',
            field=models.CharField(max_length=4, null=True, verbose_name='photo_column_url'),
        ),
    ]
