# Generated by Django 2.1.3 on 2018-12-05 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='avatar',
            field=models.CharField(default='../assets/avatar-default.jpg', max_length=100),
        ),
    ]
