# Generated by Django 2.1.3 on 2018-12-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0002_auto_20181205_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='avatar',
            field=models.CharField(default='avatar-default.jpg', max_length=100),
        ),
    ]
