# Generated by Django 2.1.3 on 2018-12-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0003_auto_20181205_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='avatar',
            field=models.CharField(default='/images/avatar/avatar-default.jpg', max_length=100),
        ),
    ]
