# Generated by Django 2.1.3 on 2018-12-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0004_auto_20181205_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='avatar',
            field=models.ImageField(default='/images/avatar/avatar-default.jpg', height_field='高度', upload_to='avatar/', width_field='宽度'),
        ),
    ]
