# Generated by Django 2.1.3 on 2018-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0005_auto_20181211_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='avatar',
            field=models.ImageField(default='/images/avatar/avatar-default.jpg', height_field='height_field', upload_to='avatar/', width_field='width_field'),
        ),
    ]
