# Generated by Django 2.1.3 on 2018-12-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0006_auto_20181211_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
