# Generated by Django 2.1.3 on 2018-12-11 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0007_auto_20181211_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='height_field',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='width_field',
        ),
    ]
