# Generated by Django 2.1.3 on 2018-12-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0010_auto_20181211_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='avatar',
            field=models.ImageField(default='/images/avatar/avatar-default.jpg', height_field='height_field', upload_to='../myspace/public/images/avatar/avatar-default.jpg', width_field='width_field'),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='height_field',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='width_field',
            field=models.IntegerField(default=0),
        ),
    ]
