# Generated by Django 2.1.3 on 2018-12-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0014_auto_20181211_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='avatar',
            field=models.ImageField(default='/media/avatar-default.jpg', height_field='height_field', upload_to='../media/', width_field='width_field'),
        ),
    ]
