# Generated by Django 2.1.3 on 2018-12-11 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0018_auto_20181211_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='avatar',
        ),
    ]
