# Generated by Django 2.1.3 on 2018-12-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0019_remove_userdetail_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='avatar',
            field=models.CharField(default='/images/avatar/avatar-default.jpg', max_length=100),
        ),
    ]
