# Generated by Django 2.1.3 on 2018-12-26 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HomeSpace', '0020_userdetail_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
